### ISSUE TITLE
De-brand site 

### ISSUE THREAD

**Issue by stockholmux** [valkey-io/valkey-website#14]
**Describe the bug**

Site looks like template: clean up the css to make it look more neutral and adopts LF colours.

See #13

**Comment by Laphatize** [comment]
Thought I'd link this here: https://www.linuxfoundation.org/brand-guidelines

**Comment by stockholmux** [comment]
@Laphatize That's helpful - we'll dig into it when we add the logos.

**Comment by stockholmux** [comment]
Closed by #15 though
